#ifndef _PINMUX_H_
#define _PINMUX_H_

/*
 *  * MODE0 - Mux Mode 0
 *   * MODE1 - Mux Mode 1
 *    * MODE2 - Mux Mode 2
 *     * MODE3 - Mux Mode 3
 *      * MODE4 - Mux Mode 4
 *       * MODE5 - Mux Mode 5
 *        * MODE6 - Mux Mode 6
 *         * MODE7 - Mux Mode 7
 *          * IDIS - Receiver disabled
 *           * IEN - Receiver enabled
 *            * PD - Internal pull-down
 *             * PU - Internal pull-up
 *              * OFF - Internal pull disabled
 *               */

#define MUX_EVM() \

/* Design Status: NO ERRORS */

MUX_VAL(CONTROL_PADCONF_GPMC_AD0, (IEN | PD | MODE7 )) /* gpio1[0] */\
MUX_VAL(CONTROL_PADCONF_GPMC_AD1, (IEN | PD | MODE7 )) /* gpio1[1] */\
MUX_VAL(CONTROL_PADCONF_GPMC_AD2, (IEN | PD | MODE7 )) /* gpio1[2] */\
MUX_VAL(CONTROL_PADCONF_GPMC_AD3, (IEN | PD | MODE7 )) /* gpio1[3] */\
MUX_VAL(CONTROL_PADCONF_GPMC_AD4, (IEN | PD | MODE7 )) /* gpio1[4] */\
MUX_VAL(CONTROL_PADCONF_GPMC_AD5, (IEN | PD | MODE7 )) /* gpio1[5] */\
MUX_VAL(CONTROL_PADCONF_GPMC_AD6, (IEN | PD | MODE7 )) /* gpio1[6] */\
MUX_VAL(CONTROL_PADCONF_GPMC_AD7, (IEN | PD | MODE7 )) /* gpio1[7] */\
MUX_VAL(CONTROL_PADCONF_GPMC_AD8, (IEN | PD | MODE7 )) /* gpio0[22] */\
MUX_VAL(CONTROL_PADCONF_GPMC_AD9, (IEN | PD | MODE7 )) /* gpio0[23] */\
MUX_VAL(CONTROL_PADCONF_GPMC_AD10, (IEN | PD | MODE7 )) /* gpio0[26] */\
MUX_VAL(CONTROL_PADCONF_GPMC_AD11, (IEN | PD | MODE7 )) /* gpio0[27] */\
MUX_VAL(CONTROL_PADCONF_GPMC_AD12, (IEN | PD | MODE7 )) /* gpio1[12] */\
MUX_VAL(CONTROL_PADCONF_GPMC_AD13, (IEN | PD | MODE7 )) /* gpio1[13] */\
MUX_VAL(CONTROL_PADCONF_GPMC_AD14, (IEN | PD | MODE7 )) /* gpio1[14] */\
MUX_VAL(CONTROL_PADCONF_GPMC_AD15, (IEN | PD | MODE7 )) /* gpio1[15] */\
MUX_VAL(CONTROL_PADCONF_GPMC_A0, (IEN | PD | MODE7 )) /* gpio1[16] */\
MUX_VAL(CONTROL_PADCONF_GPMC_A1, (IEN | PD | MODE7 )) /* gpio1[17] */\
MUX_VAL(CONTROL_PADCONF_GPMC_A2, (IEN | PD | MODE7 )) /* gpio1[18] */\
MUX_VAL(CONTROL_PADCONF_GPMC_A3, (IEN | PD | MODE7 )) /* gpio1[19] */\
MUX_VAL(CONTROL_PADCONF_GPMC_A4, (IEN | PD | MODE7 )) /* gpio1[20] */\
MUX_VAL(CONTROL_PADCONF_GPMC_A5, (IEN | PD | MODE7 )) /* gpio1[21] */\
MUX_VAL(CONTROL_PADCONF_GPMC_A6, (IEN | PD | MODE7 )) /* gpio1[22] */\
MUX_VAL(CONTROL_PADCONF_GPMC_A7, (IEN | PD | MODE7 )) /* gpio1[23] */\
MUX_VAL(CONTROL_PADCONF_GPMC_A8, (IEN | PD | MODE7 )) /* gpio1[24] */\
MUX_VAL(CONTROL_PADCONF_GPMC_A9, (OFF | OFF | MODE7 )) /* gpio1[25] */\
MUX_VAL(CONTROL_PADCONF_GPMC_A10, (IEN | PD | MODE7 )) /* gpio1[26] */\
MUX_VAL(CONTROL_PADCONF_GPMC_A11, (OFF | OFF | MODE7 )) /* gpio1[27] */\
MUX_VAL(CONTROL_PADCONF_GPMC_D0,  (OFF | OFF | MODE7 ))
MUX_VAL(CONTROL_PADCONF_GPMC_WAIT0, (IEN | PU | MODE7 )) /* gpio0[30] */\
MUX_VAL(CONTROL_PADCONF_GPMC_WPN, (IEN | PU | MODE7 )) /* gpio0[31] */\
MUX_VAL(CONTROL_PADCONF_GPMC_BEN1, (IEN | PU | MODE7 )) /* gpio1[28] */\
MUX_VAL(CONTROL_PADCONF_GPMC_CSN0, (IEN | PU | MODE7 )) /* gpio1[29] */\
MUX_VAL(CONTROL_PADCONF_GPMC_CSN1, (IEN | PU | MODE7 )) /* gpio1[30] */\
MUX_VAL(CONTROL_PADCONF_GPMC_CSN2, (IEN | PU | MODE7 )) /* gpio1[31] */\
MUX_VAL(CONTROL_PADCONF_GPMC_CSN3, (IEN | PD | MODE7 )) /* gpio2[0] */\
MUX_VAL(CONTROL_PADCONF_GPMC_CLK, (IEN | PD | MODE7 )) /* gpio2[1] */\
MUX_VAL(CONTROL_PADCONF_GPMC_ADVN_ALE, (IEN | PU | MODE7 )) /* gpio2[2] */\
MUX_VAL(CONTROL_PADCONF_GPMC_OEN_REN, (IEN | PU | MODE7 )) /* gpio2[3] */\
MUX_VAL(CONTROL_PADCONF_GPMC_WEN, (IEN | PU | MODE7 )) /* gpio2[4] */\
MUX_VAL(CONTROL_PADCONF_GPMC_BEN0_CLE, (IEN | PU | MODE7 )) /* gpio2[5] */\
/*MUX_VAL(CONTROL_PADCONF_LCD_DATA0, (IEN | OFF | MODE7 )) /* gpio2[6] */\
/*MUX_VAL(CONTROL_PADCONF_LCD_DATA1, (IEN | OFF | MODE7 )) /* gpio2[7] */\
/*MUX_VAL(CONTROL_PADCONF_LCD_DATA2, (IEN | OFF | MODE7 )) /* gpio2[8] */\
/*MUX_VAL(CONTROL_PADCONF_LCD_DATA3, (IEN | OFF | MODE7 )) /* gpio2[9] */\
/*MUX_VAL(CONTROL_PADCONF_LCD_DATA4, (IEN | OFF | MODE7 )) /* gpio2[10] */\
/*MUX_VAL(CONTROL_PADCONF_LCD_DATA5, (IEN | OFF | MODE7 )) /* gpio2[11] */\
/*MUX_VAL(CONTROL_PADCONF_LCD_DATA6, (IEN | OFF | MODE7 )) /* gpio2[12] */\
/*MUX_VAL(CONTROL_PADCONF_LCD_DATA7, (IEN | OFF | MODE7 )) /* gpio2[13] */\
/*MUX_VAL(CONTROL_PADCONF_LCD_DATA8, (IEN | OFF | MODE7 )) /* gpio2[14] */\
/*MUX_VAL(CONTROL_PADCONF_LCD_DATA9, (IEN | OFF | MODE7 )) /* gpio2[15] */\
/*MUX_VAL(CONTROL_PADCONF_LCD_DATA10, (IEN | OFF | MODE7 )) /* gpio2[16] */\
/*MUX_VAL(CONTROL_PADCONF_LCD_DATA11, (IEN | OFF | MODE7 )) /* gpio2[17] */\
/*MUX_VAL(CONTROL_PADCONF_LCD_DATA12, (IEN | OFF | MODE7 )) /* gpio0[8] */\
/*MUX_VAL(CONTROL_PADCONF_LCD_DATA13, (IEN | OFF | MODE7 )) /* gpio0[9] */\
/*MUX_VAL(CONTROL_PADCONF_LCD_DATA14, (IEN | OFF | MODE7 )) /* gpio0[10] */\
/*MUX_VAL(CONTROL_PADCONF_LCD_DATA15, (IEN | OFF | MODE7 )) /* gpio0[11] */\
/*MUX_VAL(CONTROL_PADCONF_LCD_VSYNC, (IEN | OFF | MODE7 )) /* gpio2[22] */\
/*MUX_VAL(CONTROL_PADCONF_LCD_HSYNC, (IEN | OFF | MODE7 )) /* gpio2[23] */\
/*MUX_VAL(CONTROL_PADCONF_LCD_PCLK, (IEN | OFF | MODE7 )) /* gpio2[24] */\
/*MUX_VAL(CONTROL_PADCONF_LCD_AC_BIAS_EN, (IEN | OFF | MODE7 )) /* gpio2[25] */\
MUX_VAL(CONTROL_PADCONF_MMC0_DAT3, (IEN | PU | MODE0 )) /* mmc0_dat3 */\
MUX_VAL(CONTROL_PADCONF_MMC0_DAT2, (IEN | PU | MODE0 )) /* mmc0_dat2 */\
MUX_VAL(CONTROL_PADCONF_MMC0_DAT1, (IEN | PU | MODE0 )) /* mmc0_dat1 */\
MUX_VAL(CONTROL_PADCONF_MMC0_DAT0, (IEN | PU | MODE0 )) /* mmc0_dat0 */\
MUX_VAL(CONTROL_PADCONF_MMC0_CLK, (IEN | PU | MODE0 )) /* mmc0_clk */\
MUX_VAL(CONTROL_PADCONF_MMC0_CMD, (IEN | PU | MODE0 )) /* mmc0_cmd */\
MUX_VAL(CONTROL_PADCONF_MII1_COL, (IEN | PD | MODE7 )) /* gpio3[0] */\
MUX_VAL(CONTROL_PADCONF_MII1_CRS, (IEN | PD | MODE7 )) /* gpio3[1] */\
MUX_VAL(CONTROL_PADCONF_MII1_RX_ER, (IEN | PD | MODE7 )) /* gpio3[2] */\
MUX_VAL(CONTROL_PADCONF_MII1_TX_EN, (IEN | PD | MODE7 )) /* gpio3[3] */\
MUX_VAL(CONTROL_PADCONF_MII1_RX_DV, (IEN | PD | MODE7 )) /* gpio3[4] */\
MUX_VAL(CONTROL_PADCONF_MII1_TXD3, (IEN | PD | MODE7 )) /* gpio0[16] */\
MUX_VAL(CONTROL_PADCONF_MII1_TXD2, (IEN | PD | MODE7 )) /* gpio0[17] */\
MUX_VAL(CONTROL_PADCONF_MII1_TXD1, (IEN | PD | MODE7 )) /* gpio0[21] */\
MUX_VAL(CONTROL_PADCONF_MII1_TXD0, (IEN | PD | MODE7 )) /* gpio0[28] */\
MUX_VAL(CONTROL_PADCONF_MII1_TX_CLK, (IEN | PD | MODE7 )) /* gpio3[9] */\
MUX_VAL(CONTROL_PADCONF_MII1_RX_CLK, (IEN | PD | MODE7 )) /* gpio3[10] */\
MUX_VAL(CONTROL_PADCONF_MII1_RXD3, (IEN | PD | MODE7 )) /* gpio2[18] */\
MUX_VAL(CONTROL_PADCONF_MII1_RXD2, (IEN | PD | MODE7 )) /* gpio2[19] */\
MUX_VAL(CONTROL_PADCONF_MII1_RXD1, (IEN | PD | MODE7 )) /* gpio2[20] */\
MUX_VAL(CONTROL_PADCONF_MII1_RXD0, (IEN | PD | MODE7 )) /* gpio2[21] */\
MUX_VAL(CONTROL_PADCONF_RMII1_REF_CLK, (IEN | PD | MODE7 )) /* gpio0[29] */\
MUX_VAL(CONTROL_PADCONF_MDIO, (IEN | PU | MODE7 )) /* gpio0[0] */\
MUX_VAL(CONTROL_PADCONF_MDC, (IEN | PU | MODE7 )) /* gpio0[1] */\
MUX_VAL(CONTROL_PADCONF_SPI0_SCLK, (IEN | OFF | MODE7 )) /* gpio0[2] */\
MUX_VAL(CONTROL_PADCONF_SPI0_D0, (IEN | OFF | MODE7 )) /* gpio0[3] */\
MUX_VAL(CONTROL_PADCONF_SPI0_D1, (IEN | OFF | MODE7 )) /* gpio0[4] */\
MUX_VAL(CONTROL_PADCONF_SPI0_CS0, (IEN | OFF | MODE7 )) /* gpio0[5] */\
MUX_VAL(CONTROL_PADCONF_SPI0_CS1, (IEN | OFF | MODE1 )) /* uart3_rxd_mux1 */\
MUX_VAL(CONTROL_PADCONF_ECAP0_IN_PWM0_OUT, (IDIS | OFF | MODE1 )) /* uart3_txd_mux1 */\
MUX_VAL(CONTROL_PADCONF_UART0_CTSN, (IEN | OFF | MODE7 )) /* gpio1[8] */\
MUX_VAL(CONTROL_PADCONF_UART0_RTSN, (IEN | OFF | MODE7 )) /* gpio1[9] */\
MUX_VAL(CONTROL_PADCONF_UART0_RXD, (IEN | OFF | MODE0 )) /* uart0_rxd */\
MUX_VAL(CONTROL_PADCONF_UART0_TXD, (IDIS | OFF | MODE0 )) /* uart0_txd */\
MUX_VAL(CONTROL_PADCONF_UART1_CTSN, (IEN | OFF | MODE7 )) /* gpio0[12] */\
MUX_VAL(CONTROL_PADCONF_UART1_RTSN, (IEN | OFF | MODE7 )) /* gpio0[13] */\
MUX_VAL(CONTROL_PADCONF_UART1_RXD, (IEN | OFF | MODE0 )) /* uart1_rxd */\
MUX_VAL(CONTROL_PADCONF_UART1_TXD, (IDIS | OFF | MODE0 )) /* uart1_txd */\
MUX_VAL(CONTROL_PADCONF_I2C0_SDA, (IEN | OFF | MODE7 )) /* gpio3[5] */\
MUX_VAL(CONTROL_PADCONF_I2C0_SCL, (IEN | OFF | MODE7 )) /* gpio3[6] */\
MUX_VAL(CONTROL_PADCONF_MCASP0_ACLKX, (IEN | PD | MODE7 )) /* gpio3[14] */\
MUX_VAL(CONTROL_PADCONF_MCASP0_FSX, (IEN | PD | MODE7 )) /* gpio3[15] */\
MUX_VAL(CONTROL_PADCONF_MCASP0_AXR0, (IEN | PD | MODE7 )) /* gpio3[16] */\
MUX_VAL(CONTROL_PADCONF_MCASP0_AHCLKR, (IEN | PD | MODE7 )) /* gpio3[17] */\
MUX_VAL(CONTROL_PADCONF_MCASP0_ACLKR, (IEN | PD | MODE7 )) /* gpio3[18] */\
MUX_VAL(CONTROL_PADCONF_MCASP0_FSR, (IEN | PD | MODE7 )) /* gpio3[19] */\
MUX_VAL(CONTROL_PADCONF_MCASP0_AXR1, (IEN | PD | MODE7 )) /* gpio3[20] */\
MUX_VAL(CONTROL_PADCONF_MCASP0_AHCLKX, (IEN | PD | MODE7 )) /* gpio3[21] */\
MUX_VAL(CONTROL_PADCONF_XDMA_EVENT_INTR0, (IEN | OFF | MODE7 )) /* gpio0[19] */\
MUX_VAL(CONTROL_PADCONF_XDMA_EVENT_INTR1, (IEN | OFF | MODE7 )) /* gpio0[20] */\
MUX_VAL(CONTROL_PADCONF_WARMRSTN, (IEN | OFF | MODE0 )) /* nRESETIN_OUT */\
MUX_VAL(CONTROL_PADCONF_EXTINTN, (IEN | OFF | MODE0 )) /* nNMI */\
MUX_VAL(CONTROL_PADCONF_TMS, (IEN | PU | MODE0 )) /* TMS */\
MUX_VAL(CONTROL_PADCONF_TDI, (IEN | PU | MODE0 )) /* TDI */\
MUX_VAL(CONTROL_PADCONF_TDO, (IDIS | PU | MODE0 )) /* TDO */\
MUX_VAL(CONTROL_PADCONF_TCK, (IEN | PU | MODE0 )) /* TCK */\
MUX_VAL(CONTROL_PADCONF_TRSTN, (IEN | PD | MODE0 )) /* nTRST */\
MUX_VAL(CONTROL_PADCONF_EMU0, (IEN | PU | MODE0 )) /* EMU0 */\
MUX_VAL(CONTROL_PADCONF_EMU1, (IEN | PU | MODE7 )) /* gpio3[8] */\
MUX_VAL(CONTROL_PADCONF_RTC_PWRONRSTN, (IEN | OFF | MODE0 )) /* RTC_porz */\
MUX_VAL(CONTROL_PADCONF_PMIC_POWER_EN, (IDIS | PU | MODE0 )) /* PMIC_POWER_EN */\
MUX_VAL(CONTROL_PADCONF_EXT_WAKEUP, (IEN | PD | MODE0 )) /* EXT_WAKEUP */\
MUX_VAL(CONTROL_PADCONF_RTC_KALDO_ENN, (IEN | OFF | MODE0 )) /* ENZ_KALDO_1P8V */\
MUX_VAL(CONTROL_PADCONF_USB0_DRVVBUS, (IDIS | PD | MODE0 )) /* USB0_DRVVBUS */\
MUX_VAL(CONTROL_PADCONF_USB1_DRVVBUS, (IDIS | PD | MODE0 )) /* USB1_DRVVBUS */\

#endif

